version: '2'

services:
  drupal:
    image: drupal:8.8.2 
    ports:
      - '8080:80'
    environment:
      - DATABASE_TYPE: PostgreSQL 
      - DATABASE_HOST: postgres-db
      - POSTGRES_DB: drupal
      - POSTGRES_USER: drupal-user
      - POSTGRES_PASSWORD: drupal-password
  postgres-db:
    image: postgres:12.1
    environment:
      - POSTGRES_DB: drupal
      - POSTGRES_USER: drupal-user
      - POSTGRES_PASSWORD: drupal-password
