version: '2'

services:
  drupal:
    #When we add a build + image value to a compose service, it knows to use the image name to write to in our image cache rathen than pull it from Docker Hub
    image: drupal-custom:8
    ports:
      - '8080:80'
    build:
      context: .   
    environment:
      DATABASE_TYPE: PostgreSQL
      DATABASE_HOST: postgres-db
      POSTGRES_DB: drupal
      POSTGRES_USER: drupal-user
      POSTGRES_PASSWORD: drupal-password
    volumes:
      # assign to a named volume (folder not specified in the volume creation and not possibile without a specific plugin)
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      # assign to a specific folder
      - ./volumes/drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
  postgres-db:
    image: postgres:12.1
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: drupal-user
      POSTGRES_PASSWORD: drupal-password
    volumes:
      - drupal-data:/var/lib/postgresql/data
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-data:
